### ISSUE TITLE
Request regarding CONST command

### ISSUE THREAD

**Issue by Jaan-Doh** [totalspectrum/flexprop#43]
I do not have any problems with how the command CONST works.
It's more an AESTHETIC query/request.

I note the command is FIXED to the Left Margin and no tabs or leading spaces are permitted before the keyword CONST.
Would it be possible (in future versions) to ALLOW for leading spaces to be used before the keyword CONST?

Thanks

JD

**Comment by drawkula** [comment]
BASIC? P1? P2?

**Comment by totalspectrum** [comment]
Could you give an example of something that doesn't currently work that you would like to have work? I've tried CONST in Basic and it seems fine with tabs and spaces before it. I admit the documentation is a little bit misleading, since it says "at the beginning of a line" where it really means "before any other non-white space characters on a line". Is that what is confusing?

**Comment by Jaan-Doh** [comment]
It was Basic 
I'm using Version 5.20
And your quite right it does indeed work. Sorry for your wasted time.

JD
